version: '2'
services:
  mysql:
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
  limesurvey:
    depends_on:
      - mysql
    ports:
      - "80:80"
    volumes:
      - upload:/app/upload
    image:
      crramirez/limesurvey:latest
volumes:
  mysql:
  upload:
